### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by ShalokShalom** [Light-Team/ModPE-IDE-Source#1]
Is it possible to implement this language? https://github.com/fable-compiler/Fable

**Comment by KillerBLS** [comment]
Maybe... but seriously - i don't know, it needs to be tested 😫

**Comment by ShalokShalom** [comment]
I can test it, once it is initially implemented. :)

**Comment by max-pasichnyk** [comment]
Hi. Yes, it is possible.

**Comment by KillerBLS** [comment]
I talked with @max-pasichnyk, he will help me to implement F# **in early 2018** (in future updates).

**Comment by ShalokShalom** [comment]
Thanks, fine ^_^

**Comment by massivemadness** [comment]
Finally, added in [v2025.1.3](https://github.com/massivemadness/Squircle-CE/releases/tag/2025.1.3) 😄
