### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [Light-Team/ModPE-IDE-Source#3]
Would you mind publishing the APK here at Github (e.g. via `releases/`, see [Creating releases](https://help.github.com/articles/creating-releases/) in the Github Help) for folks without Playstore to grab it? I'd then offer to serve it via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid), including automated updates.

**Comment by KillerBLS** [comment]
https://github.com/Light-Team/ModPE-IDE-Source/releases

**Comment by ShalokShalom** [comment]
Great idea. Thanks ^-^

**Comment by IzzySoft** [comment]
> This is old release from 2017, you can download new from Google Play store:
https://play.google.com/store/apps/details?id=com.KillerBLS.modpeide

Version in `releases/`: 6.2.2017  
Version at Playstore: 2018.1.0

So the version here is (if I read the version number correctly) almost a year older than the current one at playstore?

Sorry, that doesn't make much sense (if I can no longer keep an app updated, I usually remove it from my repo – not the other way around; I don't want to give people "false hopes"). We'd need the new version whenever available. My updater cannot fetch from Playstore. Any chance you'll keep the `releases/` updated, @KillerBLS?

**Comment by KillerBLS** [comment]
@IzzySoft I can upload new versions in `/releases`, but I don't think I will update the source code...

**Comment by IzzySoft** [comment]
@KillerBLS That would be fine for me. For the F-Droid main repo, it would be fine the other way around.

Being curious: the license states GPL; is the app no longer open source, or did the source just move to a different place? Or did you just mean you won't place the tags to reflect the match for the APK? In the latter case: no need to make that for all past releases indeed, full ack! But doing so for future ones wouldn't hurt :wink:

**Comment by KillerBLS** [comment]
@IzzySoft Open source is not available right now, but i think, I'll upload it later (in this year)

**Comment by ShalokShalom** [comment]
This year is long ^-^

**Comment by IzzySoft** [comment]
@MassiveMadness if it's open source again and the source openly available, consider moving the app to the main repo. Thanks to the fact you removed the NonFreeDeps (GMS and Firebase), it should now fit there. Of course I have no problems keeping your app in my repo – but the main repo has more prestige (and trust).
